########################################################
# profile配置
#profile:
#  active: dev

########################################################
# 应用配置
app:
  name: dartboot # 应用名可以自定义修改

########################################################
# 服务配置
server:
  port: 8701 # 端口可以自定义修改
  context-path: /dartboot # 上下文可以自定义修改

database:
  mongo:
    db1:
      hosts:
      - 192.168.1.xx:27017
      username: xxxx
      password: xxxx
      db: xxx
      pool-size: 10